### PR TITLE
Revert "Revert "devise""

### PR DESCRIPTION
**Pull request by jacobwgillespie**
Reverts pawn-stars/chess-app#7 to add back devise

### CODE REVIEW

**Comment by jimxlin** [comment]
Looks good to me.

**Comment by jacobwgillespie** [comment]
@miljinx since this PR merging may block your model branch, here's a handy git collaboration trick: you can base a branch on another branch:

```shell
$ git fetch origin
$ git checkout revert-7-revert-6-add_devise
$ git checkout -b my-new-branch
```

Then `my-new-branch` is based on `revert-7-revert-6-add_devise`, so you can start development with the changes from this one already present.  You can even open a PR without this one merged - it will have the changes from both branches so I'd recommend adding a note `Depends on #123` to the top of any early PRs.  Then once this one merges, yours will be free to merge.

**Comment by jimxlin** [comment]
Thanks, that's a very handy feature I was not aware of.

**Comment by mreynolds0142** [comment]
:+1:

**Pull request merged**
