### PR TITLE
devise

### PR DESCRIPTION
**Pull request by brianedwardhussey**
Installed devise.

### CODE REVIEW

**Comment by jimxlin** [comment]
I don't know if the issues with Travis CI can be safely ignored. I'll wait for Jacob to approve this since he seems to be more familiar with it.

**Review by jacobwgillespie — CHANGES_REQUESTED** [review]
So because of how we had to reset your git environment, this PR actually reverts a few of the changes made to master, specifically the `.travis.yml` is being deleted and the `README.md` is being altered.  You probably want to either recreate this branch with those changes omitted, or since it's just two files, you can grab their contents from master [here](https://github.com/pawn-stars/chess-app/blob/master/.travis.yml) and [here](https://github.com/pawn-stars/chess-app/blob/master/README.md), make sure your local branch looks the same, then add another commit to restore them to their previous state.

Other than that, this looks good to me.  I also requested that @miljinx review this one as I think he named the player model Player and the model name here is User.  We only need one, so we should rename one of those.

**Comment by jacobwgillespie** [comment]
Oh, and the Travis CI error will go away once the `.travis.yml` file is back - it's just complaining about missing its configuration file.  (you can click on the Details link next to the failed Travis build to see all the output from when it tried to run the tests)

**Comment by jimxlin** [comment]
I think leaving the model as User is fine. I haven't actually generated any models yet, so I will leave this one as is.

**Comment by jacobwgillespie** [comment]
Sorry this probably wasn't super clear - we should let the PR author perform the PR merge.  That way they can make sure there aren't any final necessary changes, etc.  

There's two changes needed to this PR before it's able to be merged, so I reverted this PR merge and added those two changes to a new PR #8.  I'll let @brianedwardhussey review that one before merge.

Anyways, no worries 👍

**Comment by jimxlin** [comment]
Sorry, I forgot about that. I'll keep that in mind.

**Pull request merged**
